### ISSUE TITLE
No API key in preferences.

### ISSUE THREAD

**Issue by theunbob** [fwenzel/copy-shorturl#100]
When clicking the 'copy-shorturl' icon, "No API key in preferences" message is displayed. What is the meaning of this message and what action do I take to correct?

I'm running Firefox 68.0 on Windows 10 Home 1903.

![CopyShorturl](https://user-images.githubusercontent.com/25568254/61662088-7cbd0880-ac82-11e9-96de-29e49acdfd5b.PNG)

Oops! My bad. I overlooked 'Bitly Generic Access Token (Generate an API key with Bitly)' on the options page. Not a bug!

**Comment by theunbob** [comment]
Oops! My bad. I overlooked 'Bitly Generic Access Token (Generate an API key with Bitly)' on the options page. Not a bug!

**Comment by fwenzel** [comment]
Oh glad you found the problem! Hope you enjoy the add-on otherwise!!
