### ISSUE TITLE
bit.ly API V4

### ISSUE THREAD

**Issue by HiggiML** [fwenzel/copy-shorturl#108]
I've received the following email several times from bit.ly re: updating to their V4 API.

"Dear Bitly Customer,  Our records show your organization is still actively generating Bitly links using Bitly API V3 that is no longer supported as of March 1, 2020. You must complete your migration to API V4 no later than March 31 in order to avoid any disruptions to your work..."

It's not as simple as changing V3 to V4 in the Custom URL section of Copy ShortURL.
     https://api-ssl.bitly.com/v3/shorten?format=txt&access_token=[MyTokenHere]&longUrl=%URL%

How do I get the Copy ShortURL Add-On to use bit.ly's V4 API?  Thanks a bunch!

**Comment by fwenzel** [comment]
Thank you! This is super helpful. I'll have to upgrade the API code, I have to check the documentation.

Thank you for saving me! I didn't know!!!

**Comment by fwenzel** [comment]
Okay I wrote the new code and tested it, it works. I will release version 5.1.0 shortly!

**Comment by HiggiML** [comment]
Yabba dabba doo!  With your previous documentation, I was able to stumble through creating a bit.ly access token and using the custom url https://api-ssl.bitly.com/v3/shorten?format=txt&access_token=[MyTokenHere]&longUrl=%URL%.  What do I need to tweak to use the new V4 API?  Thanks!

**Comment by fwenzel** [comment]
This URL is for version 3 of the bitly API and *will* stop working next week.

To get back to normal:
* make sure you have version 5.1.0 (automatic update from Mozilla add-ons site)
* switch to bitly as shortening service
* copy your API token into the required field
* save

Should work, it works for me:
<img width="450" alt="image" src="https://user-images.githubusercontent.com/87232/77257970-cfe1c380-6c34-11ea-8b99-c5b48902ab32.png">

**Comment by HiggiML** [comment]
Ah!  Easy Peasy.  Thank you.
