### ISSUE TITLE
shortlink is not parsed on some sites

### ISSUE THREAD

**Issue by pipiscrew** [fwenzel/copy-shorturl#121]
Is not getting the ready **shortlink tag** on many pages, ex : 
https://www.pipiscrew.com/2021/08/jj-still/
https://www.makeleio.gr/?p=3881024

but on this, is working fine
https://pmig96.wordpress.com/2021/04/29/palmos-on-raspberry-pi/

---

I execute the code of `data/js/discover/default.js` on console and working fine (result the shortlink), possible somewhere before stumble.

**Comment by fwenzel** [comment]
Thank you for filing this - I will check the pages you are talking about. It is possible that something is messing with the message passing between the page and the add-on :o

I appreciate your report!

**Comment by fwenzel** [comment]
I re-confirmed that this URL `https://www.makeleio.gr/?p=3881024` works correctly. I wonder if this was a bug in the Mozilla add-ons framework that now went away. I will close this for now, but please reopen if you encounter more issues!
