### ISSUE TITLE
Can you restore is.gd as the default shortener?

### ISSUE THREAD

**Issue by DrBB01** [fwenzel/copy-shorturl#127]
I saw your note on the most recent version that is.gd was no longer working. FWIW, I am able to go directly to the website (https://is.gd) and shorten a URL manually by entering it into the shortening bar. Perhaps the site was under construction for awhile and is now repaired, or is there another issue with respect to using it with a Firefox extension? Thanks for your consideration!
DrBB01

**Comment by fwenzel** [comment]
OMG!!!! THEY FIXED IT!!!! OMG!

I'll re-add it. I love is.gd I just thought they were gone forever!

**Comment by fwenzel** [comment]
I'll re-add the code and push an updated version of the add-on probably later today.

Thank you for pointing this out to me!

**Comment by DrBB01** [comment]
Hi Fred,

I may not be quite as excited as you are, but I am very happy that you can
bring is.gd back! It has been my go-to shortener for years. Looking forward
to the next update!

Best,

Bruce

**Comment by fwenzel** [comment]
Done - should update itself in a little while!

**Comment by DrBB01** [comment]
Fred,

👍
