### ISSUE TITLE
kutt.it support

### ISSUE THREAD

**Issue by waclaw66** [fwenzel/copy-shorturl#128]
Please add support for custom kutt.it service. It uses POST requests.
https://docs.kutt.it/#tag/links/paths/~1links/post

**Comment by fwenzel** [comment]
Sounds good, I can do that.

Note that kutt.it requires an API key. I have that ability for bitly right now but have to make it a little more generic.

You'll then have to make an account with kuttly and copy and paste the API key into the copy shorturl settings.

**Comment by fwenzel** [comment]
I added this and will upload version 5.4.0 to Mozilla now!

**Comment by waclaw66** [comment]
Thanks, actually I'm running it on own domain, could you please add this option as well? Thanks.

**Comment by fwenzel** [comment]
Oh interesting. Yeah sure

**Comment by fwenzel** [comment]
Added -- I'll ship a new version shortly and you should be able to either leave the custom domain field empty or put a domain in that you registered with kutt.it

**Comment by waclaw66** [comment]
A sorry, that was a missunderstanding. I meant support for Kutt running on own server, meaning access custom domain directly instead of https://kutt.it to keep data in privacy.

**Comment by fwenzel** [comment]
Oh I did not realize. Maybe - that's getting very specific and I need features to be broadly applicable to users. There is a function already for leveraging a GET request API, maybe kutt supports that?

**Comment by waclaw66** [comment]
Unfortunately Kutt uses POST only, therefore I mentioned an idea to add POST support to custom service configuration of this addon to more generic.
