### ISSUE TITLE
amzn.com shortened links are incorrect

### ISSUE THREAD

**Issue by meeotch** [fwenzel/copy-shorturl#129]
I use the Copy ShortURL addon for firefox, and it works great in general.  However, with amazon pages, it produces incorrect links:

 https://www.amazon.com/Pieces-Cute-Plush-Frog-Hat-Earflap-Soft-Ski-Hat-Full-Headgear-Novelty-Party-Dress-Cosplay-Costume/dp/B08SM3CDDN

becomes:

https://amzn.com/B08SM3CDDN

which doesn't point to a valid page.  You need to insert "dp" into it to make it work:

https://amzn.com/dp/B08SM3CDDN

**Comment by fwenzel** [comment]
Oh no! Thank you for filing this! I'll fix it tomorrow.

**Comment by fwenzel** [comment]
Fixed! Thanks again this was super helpful. They definitely changed that at some point.

**Comment by fwenzel** [comment]
I'm uploading a new version to Mozilla momentarily.

**Comment by meeotch** [comment]
Now that's service!  I can confirm the fix - thanks.

mitch
