### ISSUE TITLE
git.io is shut down

### ISSUE THREAD

**Issue by fwenzel** [fwenzel/copy-shorturl#132]
git.io is showing a banner now " Sorry, we're no longer accepting new links to shorten. "

Looks like the service is being shut down.

Need to remove the special shortener code for github.

**Comment by foolioo** [comment]
> You can no longer create new URLs on git.io. Existing URLs will continue to be accessible, but we encourage using one of the many URL shortening services that are available, instead of git.io, as we will be deprecating the tool in the future.  [_source_](https://github.blog/changelog/2022-01-11-git-io-no-longer-accepts-new-urls/)

![image](https://user-images.githubusercontent.com/28758375/169228795-4a5a635b-36c9-45b1-be53-5b7bbd9bffcf.png)

any intention to fix this soon or shall we seek an alternative?

**Comment by fwenzel** [comment]
Oh! It did get shut down didn't it. My apologies. I will fix the add-on shortly.

**Comment by fwenzel** [comment]
@foolioo I submitted v5.5.0 to the Mozilla add-ons website, and it should update itself as soon as it is reviewed by Mozilla. 🥳

**Comment by foolioo** [comment]
it works for me now, thanks @fwenzel
