### ISSUE TITLE
Right click on link, shorten that link

### ISSUE THREAD

**Issue by fwenzel** [fwenzel/copy-shorturl#39]
... and maybe load that document in the background to determine the canonical URL of the target?

Though this could have side effects. Hmmmm

**Comment by Caspy7** [comment]
Or you could just ignore the canonical URL and just use the default service. Then you could probably implement this feature pretty quickly.

**Comment by fwenzel** [comment]
@Caspy7 that's exactly what I ended up doing!

**Comment by fwenzel** [comment]
Thank you
