### ISSUE TITLE
Add "Copy ShortURL at this time" item for Youtube

### ISSUE THREAD

**Issue by Caspy7** [fwenzel/copy-shorturl#45]
Youtube simply adds something like ?t=2m7s to the end of short URLs in order to start a video at that particular time.
Please consider adding an additional item to the context menu for youtube pages that will preserve the current time.  By my count it takes five clicks to copy the URL for the current time with youtube's method.

**Comment by fwenzel** [comment]
This is a nice suggestion! YouTube is also common enough that it's not too crazy a feature for a generic add-on like this.

**Comment by fwenzel** [comment]
Actually, their feature is pretty straightforward.

STR:
* Play a video on youtube.
* Right-click on the player. "get video URL at this time"
* it shows you the URL and asks you to copy. Press CMD+C and escape to close.

If it was somewhat hidden, I'd probably add it, but their feature seems good enough to me.

**Comment by fwenzel** [comment]
Closing this. I'm not generally opposed to add site-specific features to my add-ons, but I'm not quite convinced of the use case here.
