### ISSUE TITLE
Remove general 'Copy ShortURL' item when right clicking links

### ISSUE THREAD

**Issue by Caspy7** [fwenzel/copy-shorturl#51]
I'm a big fan of a non-cluttered context menu and I've removed addons before because they added extra options to context menus I didn't need.

When right clicking on links, the only additional option available should be 'Copy ShortURL for this link'.  
(I remember when the Mozilla Suite's context menu literally filled the screen (top to bottom) because it contained all possible options rather than being, well, contextual.)

Browser user conventions now train the user to expect menus to be contextual in this manner and beyond being more cluttered (IMO) this can be a bit confusing.  In fact, previously I used this option when right clicking a link thinking I was getting the shortURL for that link (before the link menu was added).

**Comment by fwenzel** [comment]
Thank you! This is a very valuable contribution, and I agree with it. I'll make it happen.

**Comment by fwenzel** [comment]
For instance, I see "view page source" in the page's context menu, but not in the link context menu.

**Comment by fwenzel** [comment]
(and sorry I missed this bug for a few days, no ill intent)
