### ISSUE TITLE
Add-on doesn't pick up sl-SI locale

### ISSUE THREAD

**Issue by ghost** [fwenzel/copy-shorturl#55]
Hi!

When I install the add-on, the locale remains in English. Perhaps changing the folder name to "sl" would work, since the "general.useragent.locale" setting in Slovenian Firefox is "sl".

Best regards,
   Peter

**Comment by fwenzel** [comment]
That is probably true. I'll give it a look!

**Comment by fwenzel** [comment]
Since this is a rewrite now, the previous translations went away.

**Comment by fwenzel** [comment]
PS: This was still useful, I'll figure out how to verify translation codes when languages are readded.
