### ISSUE TITLE
is.gd shortener broken (HTTPS)

### ISSUE THREAD

**Issue by fwenzel** [fwenzel/copy-shorturl#60]
From [a review](https://addons.mozilla.org/en-US/firefox/addon/copy-shorturl/reviews/813813/reply):

> It does not work on Firefox 48.0.1 and 50.0a2.
After check, I found that it is the is.gd problem.
It migrate to HTTPS only, but this addons still use HTTP.
https://is.gd/news.php

**Comment by meteormatt** [comment]
I added Pull Request on #59, can you merge it?

**Comment by fwenzel** [comment]
Argh lol I am silly and missed that.

**Comment by fwenzel** [comment]
Duplicate of #59, my fault.
