### ISSUE TITLE
Creation of short URL broken

### ISSUE THREAD

**Issue by meteormatt** [fwenzel/copy-shorturl#68]
Open https://addons.mozilla.org/zh-CN/firefox/ ,right click Copy ShortURL, but do not have result.

**Comment by fwenzel** [comment]
ugh, I wonder what broke this time. Probably a change in Firefox?

**Comment by fwenzel** [comment]
thank you

**Comment by fwenzel** [comment]
Sorry I thought these were two different bugs, but you're right there is just one.

Firefox restricts add-ons from running on restricted pages such as AMO. (duping this against #69)
