### ISSUE TITLE
AMO short url "missing host permission"

### ISSUE THREAD

**Issue by fwenzel** [fwenzel/copy-shorturl#69]
Creating a URL on addons.mozilla.org is throwing an error:

> Error: Missing host permission for the tab

Hmmm.

**Comment by fwenzel** [comment]
Aha! Add-ons do not work on restricted pages such as `about:` and AMO. I just need to catch and expose the error.

**Comment by meteormatt** [comment]
So can not get short URL for AMO now?

**Comment by fwenzel** [comment]
Correct. It is possible that there is a workaround but by default add-ons do not have the necessary permissions needed to run on AMO.
