### ISSUE TITLE
Option: No external service

### ISSUE THREAD

**Issue by ckleemann** [fwenzel/copy-shorturl#79]
It would be nice if there where an option to select None as service. Copy-short-url then returns the canonical or long url if it could not found a short url.

**Comment by fwenzel** [comment]
Oh, that's a nice feature. I can do that. Thank you!

**Comment by fwenzel** [comment]
Oh thanks for asking, didn't know it was so popular a request. This does not appear to be hard to add at all :o

**Comment by fwenzel** [comment]
I just published version 4.5.1 on Firefox Add-ons, once the update lands, you should be able to select this in the settings!
