### ISSUE TITLE
Notification does not show up

### ISSUE THREAD

**Issue by MDJonas** [fwenzel/copy-shorturl#81]
I'm using this extension with FireFox 57 -- it's excellent!  However, I checked the 'show notification on success," but that doesn't come up anywhere -- that is, there's no confirmation the shortening/copying has been done.

**Comment by fwenzel** [comment]
Did you press Save? Notifications are the default behavior.

**Comment by fwenzel** [comment]
Does the copying work right, except the notification does not show up?

<img width="395" alt="screenshot 2017-11-29 16 15 26" src="https://user-images.githubusercontent.com/87232/33406183-89127632-d520-11e7-85df-ed5ec80ef636.png">

Also, what operating system are you on?

**Comment by MDJonas** [comment]
Yes, the copy function works, but there’s no indiction on the toolbar that the extension actually shortened and copied the URL to the clipboard.  It’s not a big deal, but it would be nice to know Copy ShortURL worked without having to wait to try and paste it somewhere.

I’m running the current version of High Sierra, and FireFox 57.

Michael

**Comment by fwenzel** [comment]
Very curious. The screenshot above is the notification I see when I have the setting switched on.

**Comment by fwenzel** [comment]
Do you see that as well? You say "there's no indication in the toolbar", what are you expecting to see?

**Comment by MDJonas** [comment]
Hi Fred - 

There was no screenshot.  But I thought a small dialog would appear at the extension icon showing the successful copy/shortening.  For example, right now if I put my pointer on the  icon, the Copy URL comes up (see attached screenshot).  But when I think click in the icon to copy/shorten, nothing appears.




Michael

“Time flies like an arrow,
Fruit flies like a banana.”

8602 E. Via de VIva
Scottsdale, AZ 85258
(480) 991 0106

**Comment by fwenzel** [comment]
I suggest you check your settings about system notifications, which I believe Firefox uses. The extension just uses the Firefox API for it and shows the notification you can see in the comment above. If you can't see that, it's probably not the extension that's broken. Sorry!

**Comment by MDJonas** [comment]
Perfecto — I would never have thought of that.  For the most part, I keep notifications OFF (other than email, reminders, etc.).  But when I turned on Banner for FF, sure enough, up came the confirmation notice.

Thank you — for your patience, a great extension, and for solving the issue for me.

May the Bluebird of the Holidays fly over you.

Michael


“Time flies like an arrow,
Fruit flies like a banana.”

8602 E. Via de VIva
Scottsdale, AZ 85258
(480) 991 0106

**Comment by fwenzel** [comment]
I am happy to hear this was it! Have a great holiday season as well!
