### ISSUE TITLE
Putting a carriage return line feed on copy?

### ISSUE THREAD

**Issue by snowbound** [fwenzel/copy-shorturl#82]
I noticed that the extension seems to be putting a carriage return line feed character into the Windows clipboard at the end of the copied string. Is this by design?

**Comment by fwenzel** [comment]
No, it is not! What URL shortening service do you use? Does this happen with every URL?

**Comment by snowbound** [comment]
Using bit.ly. What I do is I use the extension and is copies it to the Win7 clipboard then I paste the clipboard contents into IRC chat client mIRC text input box. I always see a new line feed being inserted.

**Comment by fwenzel** [comment]
Thank you this is very useful. For the record I don't do anything in particular with the return value, so I probably just have to make sure to strip whitespace in the right spot.

**Comment by fwenzel** [comment]
I manually triggered the bitly code and I can confirm that there is a a line feed (not: carriage return) at the end of it. I can confirm that this *is* copied straight into the clipboard.

Nice find!

<img width="552" alt="screenshot 2017-12-07 10 08 56" src="https://user-images.githubusercontent.com/87232/33731069-cfcb51ae-db36-11e7-8e2d-28f50db3928e.png">

**Comment by fwenzel** [comment]
I just published version 4.5.1 on Firefox Add-ons, once the update lands, the line feed should be gone!
