### ISSUE TITLE
Use dedicated rules or shortening service for special sites

### ISSUE THREAD

**Issue by notatestuser** [fwenzel/copy-shorturl#83]
git.io is the official URL shortener by GitHub for GitHub, GitHub Gist and GitHub Pages links.

Really useful extension, thanks!

**Comment by fwenzel** [comment]
What's the use case? How would it work?

It looks like the URL shortener only works on github links:
<img width="855" alt="screenshot 2017-12-05 16 14 27" src="https://user-images.githubusercontent.com/87232/33637722-7b267fb2-d9d7-11e7-8967-9ea1a62e90db.png">

**Comment by notatestuser** [comment]
Yes, it could only work on GitHub. If site specific shortners are beyond scope then let me know but I saw this in the description of the Firefox addon: 

> A number of major websites expose their own short URLs for any entry on their webpages, among these: youtube (“youtu.be/…”), flickr (“flic.kr/…”), Wordpress.com, Arstechnica, Techcrunch, and many more.

> If, however, the site does not name its own short URL, the add-on automatically falls back to making a short URL using is.gd

So are you implying that this extension does not actually support site specific URL shorteners?

Thanks.

**Comment by fwenzel** [comment]
Hmmm this is an interesting issue. The sites mentioned above expose these short URLs *in their HTML source code*. I'll give you an example from [arstechnica](https://arstechnica.com/gadgets/2017/12/apple-pay-cash-hits-apple-watches-with-watchos-4-2-release/):

<img width="1102" alt="screenshot 2017-12-06 11 43 26" src="https://user-images.githubusercontent.com/87232/33681885-b3a360b4-da7a-11e7-91c8-d2e9390c5e53.png">

That means, the extension can analyze the HTML code and fish out this URL.

What the extension *doesn't* currently do is call a specific 3rd party service for generating a special shorturl for a site.

This is an interesting feature suggestion though. I know at least two use cases:
* git.io for github
* bit.ly will shorten [amazon to amzn.to](https://techcrunch.com/2010/04/14/amazon-goes-pro-with-bit-ly/) and [NY Times will shorten to nyti.ms](https://bits.blogs.nytimes.com/2009/12/16/the-times-and-bitly-roll-out-nytims-short-links/)

These neat URLs only work if you use the "correct" shortening service.

**Comment by fwenzel** [comment]
I'll keep this as a feature suggestion, thank you very much!

Maybe a setting "use special shortening service for known sites" (amzn.to, nyti.ms, git.io), and if that's enabled, then a URL from these known domains will go to that shortening service instead of the fallback one. If an error occurs, we'll use the fallback.

**Comment by notatestuser** [comment]
Thank you for that explanation. Now I understand what is going on here!

**Comment by fwenzel** [comment]
Youtube broke its short URL code (#85). This can probably be fixed(?) by having special code for it here.

**Comment by fwenzel** [comment]
^^ #63 is sort of a dupe -- it would fish the nonstandard URL out of the page somewhere as opposed to "just" using a dedicated shortening service. That might be brittle, so it would need a solid fallback for sure.

**Comment by notatestuser** [comment]
Maybe there's some API out there to leverage for that?

**Comment by fwenzel** [comment]
Good call. Maybe I'll make a simple extensible module structure with fallback, that can create or determine the right URL for a given page, and fall back gracefully as needed.
