### ISSUE TITLE
Preference to include URL hash in shortened URL

### ISSUE THREAD

**Issue by eight04** [fwenzel/copy-shorturl#86]
If I shorten the URL manually on "is.gd" website, the hash part isn't trimmed. I would like to keep the hash part so it can point to a specified section in the document, like:

https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files

**Comment by fwenzel** [comment]
That's expected behavior for whole-page URLs. (i.e., when you right click on the page itself). When you right click on a link and choose "copy shorturl for this link" it works.

**Comment by eight04** [comment]
Right click on the link does work 👍. However, could we have an option to disable trimming on whole-page URLs? It's more convienient to just click on the toolbar button without finding the link then access the command in right-click context menu. I think there are also some situations that the hashed link is not displayed on the page but generated from JavaScript.

**Comment by fwenzel** [comment]
Yes this is a good idea. Thank you for the suggestion! I will edit the description of this Issue to reflect this feature request. Happy 2018!
