### ISSUE TITLE
Nothing placed on clipboard-Firefox 58/Windows 10

### ISSUE THREAD

**Issue by peteypoo** [fwenzel/copy-shorturl#89]
Clicking the tool bar icon pops up the notification, but the clipboard still contains the old value that was placed there previously.

Is it possibly a Firefox setting?

**Comment by fwenzel** [comment]
Oh this is interesting, thank you for pointing it out. I do not have Windows 10, so it will be hard for me to reproduce if it only happens on Win :-/

**Comment by fwenzel** [comment]
What page is this happening on? Anything suspicious in the JavaScript console?

**Comment by peteypoo** [comment]
This happens on all pages.  JavaScript console shows nothing.
Sorry to leave you, but I've taken my business to one of your 'competitors' :-)

Good luck!

**Comment by fwenzel** [comment]
lol, whatever works for you. I'll double-check that the add-on still works as expected for everyone else.

**Comment by xh6ynr21y** [comment]
this issue happens to me on macos high sierra 10.13.4 and firefox 59.0.2.
it works neither with the keyboard shortcut (cmd+shift+l), not the right click context menu.

any idea?

**Comment by y0y0z** [comment]
anyone??

**Comment by fwenzel** [comment]
I'll double check what's happening. Sometimes Firefox APIs change and add-ons silently break without the developer noticing. Ugh.

**Comment by fwenzel** [comment]
Unfortunately I still cannot reproduce this issue, and I do not have Windows 10 to test further with :-/

**Comment by fwenzel** [comment]
I'll see if I can reproduce this on an instance of https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by fwenzel** [comment]
I was unable to reproduce this on Windows.

**Comment by invalidbeard** [comment]
I'm having this issue now. Windows 7 Ultimate 64 bit.

**Comment by fwenzel** [comment]
Closing this for now, since it seems impossible to reproduce. Please reopen if you can help narrow this down thank you :)
