### ISSUE TITLE
Get option to copy image URL

### ISSUE THREAD

**Issue by Xebtria** [fwenzel/copy-shorturl#90]
Currently, the extension only has the option of shortening the URL of the link (if it is a link) or the whole page if I just right click somewher on the page.
It would be nice to have an option to shorten the location of the image location as well.
and even better would be, if it is an image which is a url as well, then show the option to shorten either the URL or the image source.

I hope you understand what I mean and I'd really to see this being implemented.

**Comment by fwenzel** [comment]
I think this is a great idea!

**Comment by Xebtria** [comment]
Great! looking forward to it :)

**Comment by fwenzel** [comment]
I added img src URL shortening (will land in the next version), but "if it is an image which is a url as well, then show the option to shorten either the URL or the image source." that would mean we have to do optical character recognition, which is far outside of this extension's goals :)
