### ISSUE TITLE
Fails to Fully Preserve Link from Send.Firefox.com

### ISSUE THREAD

**Issue by mcjathan** [fwenzel/copy-shorturl#91]
I've been testing Mozilla's new secure file sharing website, send.firefox.com.  The website allows you to upload file(s), and then the website provides a URL to the file(s).  Here's an example of the URL:

https://send.firefox.com/download/2bd3b635e0/#Z_bT6uYMGtMLvPO-xJV1mg

Copy ShortURL is failing to preserve this link, and all other test links I've created on send.firefox.com.  I've tried varying the different options for Copy ShortURL and still haven't been able to get my shortened URL to work properly.  

I've also tried varying between the is.gd and tinyurl.com services and still Copy ShortURL is failing to create a proper URL.

I've also bypassed the Copy ShortURL Firefox addon, and instead created shortened links directly at the is.gd and tinyurl.com and bitly.com websites and these links work properly.

It appears that there is a bug in Copy ShortURL.

**Comment by fwenzel** [comment]
Thank you for the detailed report! I tried it out, and it seems the send.firefox site is doing something weird. I will take a look!

**Comment by fwenzel** [comment]
I found out what the problem is:
send.firefox.com uses an incorrect "og:url" meta info in its header. Which means that link sharing with copy-shorturl is broken, and it would be similarly as broken to share the link on Facebook, for instance.

I might remove og:url matching because it seems brittle and website owners often use it wrong.

**Comment by mcjathan** [comment]
That's good news, Fred!
It's kind of surprising that big, supposedly competent organizations like Mozilla and Facebook would get the header wrong!
Anyways, do you expect to release an update soon?
Regards,
Jeff


----------------------- Original Message -----------------------

**Comment by fwenzel** [comment]
Ah yes, let me do that.

**Comment by fwenzel** [comment]
Sorry for the delay, version 4.6 is now live!
