### ISSUE TITLE
Ensure produced URLs default to https

### ISSUE THREAD

**Issue by lightspeed397** [fwenzel/copy-shorturl#94]
more of a suggestion than a bug but tinyurl.com and bit.ly both default to http: protocol instead of encrypted https: .  tinyurl.com defaults to https: if you go to there site as well as bit.ly Please update extension settings to default to https:
P.S. Thank you for creating a great add-on!

**Comment by fwenzel** [comment]
Oh I am so sorry I missed this Issue! I think this is a great suggestion! I wonder why the services default to that? I am fairly certain I am using the https *API*.

**Comment by fwenzel** [comment]
I fixed it, will release an update with the next version!
