### ISSUE TITLE
ZOMG, error creating short url... Fac3b00k.

### ISSUE THREAD

**Issue by technerdchris** [fwenzel/copy-shorturl#99]
Hi,

Sadly I use the FB place a lot for work and share the URLs. I'm loving your firefox add-on otherwise though. Any thoughts about why it isn't working? 

At first I thought it was just my work computer's firefox wasn't working with the add-on but then I tried it on a not-FB page and it works. 

Thanks,
Chris

**Comment by fwenzel** [comment]
Can you give me a publicly accessible URL that it is not working on? Need steps to reproduce then I might be able to tell you what's wrong! Thanks!

**Comment by technerdchris** [comment]
Great, just went to bit.ly to see the last link that didn't work for me... [this](https://www.facebook.com/cacycleworkschris/media_set?set=a.10216428063806004&type=3) But it works on my Firefox on Kubuntu at home. It didn't work on FF Windows 10 at work. Work just has a typical router, so nothing IT-voodoo happening there.

Thanks,
Chris

**Comment by fwenzel** [comment]
Strange -- I just clicked on that and used copy-shorturl and it created this: https://bit.ly/2SSnvME

**Comment by technerdchris** [comment]
Is there something I can do on the work computer to get better feedback?

**Comment by fwenzel** [comment]
Yes the browser console might give you more info. Tools menu -> Web Developer -> Browser console ?

**Comment by fwenzel** [comment]
Closing this for now, please reopen with steps to reproduce if possible!
